data:
  test:
    module: torch.utils.data
    class: DataLoader
    DataLoader:
      dataset:
        module: flame.core.data.labelme_dataset
        class: LabelmeDataset
        LabelmeDataset:
          dirnames:
            - "'dataset/NATCOM2/train'"
            - "'dataset/NATCOM2/test'"
            - "'dataset/NATCOM2/valid'"
          classes:
            CARD_BACK_TYPE_1: 1
            CARD_FRONT_TYPE_1: 1
            CARD_BACK_TYPE_2: 1
            CARD_FRONT_TYPE_2: 1
            CARD_BACK_TYPE_3: 1
            CARD_FRONT_TYPE_3: 1
            PASSPORT: 1
            BLX: 1
          image_size: (800, 800)
          mean: [0., 0., 0.]
          std: [1., 1., 1.]
          image_patterns: ["'*.*g'", "'*.*G'"]
          label_patterns: ["'*.json'"]
      batch_size: 16
      shuffle: False
      num_workers: 12
      pin_memory: True
      drop_last: False
      collate_fn: "lambda batch:tuple(zip(*batch))"

model:
  module: flame.core.modelmodels.based_maskrcnn_resnet50_fpn
  class: MaskrcnnResnet50FPN
  MaskrcnnResnet50FPN:
    pretrained: True
    pretrained_backbone: False
    num_classes: 2
    # Anchors parameters
    anchor_sizes: "((16,), (32,), (64,), (128,), (256,))"
    aspect_ratios: "((0.5, 1.0, 2.0),) * 5"
    # Box parameters
    box_score_thresh: 0.5
    box_nms_thresh: 0.2

metrics:
  module: flame.handlers.metric_evaluator
  class: Metrics
  Metrics:
    metrics:
      coco_eval:
        module: flame.core.metric.COCO_eval
        class: COCOEvaluator
        COCOEvaluator:
          image_size: (800, 800)
          detection_path: "'checkpoint/NATCOM/maskrcnn_resnet50_fpn/2206131712/NATCOM_det_val.json'"
          ground_truth_path: "'checkpoint/NATCOM/maskrcnn_resnet50_fpn/2206131712/NATCOM_gt_val.json'"
          classes:
            CARD: 1
          output_transform: "lambda x: (x[0], x[1], x[2])"
    attach_to:
      engine: "'test'"

screenlogger:
  module: flame.handlers.screenlogger
  class: ScreenLogger
  ScreenLogger:
    eval_names:
      - "'test'"

checkpoint_loader:
  module: flame.handlers.checkpoint
  class: CheckpointLoader
  CheckpointLoader:
    checkpoint_path: "'checkpoint/NATCOM/maskrcnn_resnet50_fpn/2206131712/best_model_10_mAP=0.9979.pt'"
    mode: "'test'"

predictor:
  module: flame.handlers.predictor
  class: Predictor
  Predictor:
    evaluator_name: "'engine'"
    output_dir: "'checkpoint/NATCOM/maskrcnn_resnet50_fpn/2206131712/best_model_10_mAP=0.9979/'"
    classes:
      CARD: [[0, 255, 0], 1]
    alpha: 0.3
    draw_class: False
    draw_box: True
    image_size: (800, 800)
    use_pad_to_square: True
    output_transform: "lambda x: (x[0], x[-1])"

engine:
  module: flame.core.engine.engine
  class: Evaluator
  Evaluator:
    dataset: config['data']['test']
    device: "'cuda'"

extralibs:
  torch: torch
