data:
  train:
    module: torch.utils.data
    class: DataLoader
    DataLoader:
      dataset:
        module: flame.core.data.fasterrcnn_voc_dataset
        class: VOCDataset
        VOCDataset:
          input_dir: '''../'''
          image_size: (800, 800)
          classes:
            aeroplane: 1
            bicycle: 2
            bird: 3
            boat: 4
            bottle: 5
            bus: 6
            car: 7
            cat: 8
            chair: 9
            cow: 10
            diningtable: 11
            dog: 12
            horse: 13
            motorbike: 14
            person: 15
            pottedplant: 16
            sheep: 17
            sofa: 18
            train: 19
            tvmonitor: 20
          transforms:
            - iaa.Add(value=(-30, 30), per_channel=True)
            - iaa.GaussianBlur(sigma=(0, 1))
            - iaa.MotionBlur()
            - iaa.JpegCompression(compression=(0, 10))
            - iaa.Fliplr(p=0.5)
            - iaa.Flipud(p=0.5)
            - iaa.Grayscale(alpha=(0.0, 0.1))
            - iaa.Rot90(k=[0, 1, 2, 3], keep_size=False)
            - iaa.Affine(rotate=(0, 360), shear=(-5, 5), fit_output=True)
            - iaa.Crop(percent=(0, 0.1))
            - iaa.Pad(percent=(0, 0.1), keep_size=False)
            - iaa.ChangeColorTemperature()
          image_pattern: '''*.jpg'''
          label_pattern: '''*.xml'''
      batch_size: 16
      shuffle: True
      collate_fn: 'lambda batch:tuple(zip(*batch))'

  train_eval:
    module: torch.utils.data
    class: DataLoader
    DataLoader:
      dataset:
        module: flame.core.data.fasterrcnn_voc_dataset
        class: VOCDataset
        VOCDataset:
          input_dir: '''dataset/VOC2007/train'''
          image_size: 800
          classes:
            aeroplane: 1
            bicycle: 2
            bird: 3
            boat: 4
            bottle: 5
            bus: 6
            car: 7
            cat: 8
            chair: 9
            cow: 10
            diningtable: 11
            dog: 12
            horse: 13
            motorbike: 14
            person: 15
            pottedplant: 16
            sheep: 17
            sofa: 18
            train: 19
            tvmonitor: 20
          image_pattern: '''*.jpg'''
          label_pattern: '''*.xml'''
      batch_size: 16
      shuffle: False
      collate_fn: 'lambda batch:tuple(zip(*batch))'

  valid:
    module: torch.utils.data
    class: DataLoader
    DataLoader:
      dataset:
        module: flame.core.data.fasterrcnn_voc_dataset
        class: VOCDataset
        VOCDataset:
          input_dir: '''dataset/VOC2007/valid'''
          image_size: 800
          classes:
            aeroplane: 1
            bicycle: 2
            bird: 3
            boat: 4
            bottle: 5
            bus: 6
            car: 7
            cat: 8
            chair: 9
            cow: 10
            diningtable: 11
            dog: 12
            horse: 13
            motorbike: 14
            person: 15
            pottedplant: 16
            sheep: 17
            sofa: 18
            train: 19
            tvmonitor: 20
          image_pattern: '''*.jpg'''
          label_pattern: '''*.xml'''
      batch_size: 16
      shuffle: False
      collate_fn: 'lambda batch:tuple(zip(*batch))'

model:
  module: flame.core.model.fasterrcnn_torchvision
  class: FasterRcnnResnet50FPN
  FasterRcnnResnet50FPN:
    num_classes: 21
    pretrained: True
    pretrained_backbone: True

optim:
  module: torch.optim
  class: SGD
  SGD:
    params: config['model'].parameters()
    lr: 0.005
    momentum: 0.95
    weight_decay: 0.0005

train_evaluator:
  module: flame.handlers.metric_evaluator
  class: MetricEvaluator
  MetricEvaluator:
    dataset: config['data']['train_eval']
    device: '''cuda'''

valid_evaluator:
  module: flame.handlers.metric_evaluator
  class: MetricEvaluator
  MetricEvaluator:
    dataset: config['data']['valid']
    device: '''cuda'''

metrics:
  module: flame.handlers.metrics.metrics
  class: Metrics
  Metrics:
    metrics:
      mAP:
        module: flame.handlers.metrics.evaluator
        class: Evaluation
        Evaluation:
          evaluation_fn:
            module: flame.handlers.metrics.metric_function.mAP
            class: MeanAveragePrecision
            MeanAveragePrecision:
              num_classes: 21
              iou_threshold: 0.5
              box_format: '''corners'''
          output_transform: 'lambda x: (x[0], x[1])'
    attach_to:
      train_evaluator: '''train'''
      valid_evaluator: '''valid'''

screenlogger:
  module: flame.handlers.screenlogger
  class: ScreenLogger
  ScreenLogger:
    eval_names:
      - '''train'''
      - '''valid'''

history:
  module: flame.handlers.checkpoint
  class: History

checkpoint_loader:
  module: flame.handlers.checkpoint
  class: CheckpointLoader
  CheckpointLoader:
    checkpoint_path: ''''''
    mode: '''train'''

terminate_on_nan:
  module: flame.handlers.terminate_on_nan
  class: TerminateOnNan

lr_scheduler:
  module: flame.handlers.lr_scheduler
  class: ReduceLROnPlateau
  ReduceLROnPlateau:
    score_name: '''mAP'''
    evaluator_name: '''valid_evaluator'''
    mode: '''max'''
    patience: 5
    verbose: True

# lr_scheduler:
#   module: flame.handlers.lr_scheduler
#   class: StepLR
#   StepLR:
#     score_name: '''mAP'''
#     evaluator_name: '''valid_evaluator'''
#     step_size: 3
#     gamma: 0.1
#     verbose: True

early_stopping:
  module: flame.handlers.early_stopping
  class: EarlyStopping
  EarlyStopping:
    score_name: '''mAP'''
    evaluator_name: '''valid_evaluator'''
    mode: '''max'''
    patience: 5

best_saver:
  module: flame.handlers.checkpoint
  class: BestSaver
  BestSaver:
    dirname: '''checkpoint/VOC2007/fasterrcnn_mobilenetv3/'''
    score_name: '''mAP'''
    evaluator_name: '''valid_evaluator'''
    n_saved: 1

backup_saver:
  module: flame.handlers.checkpoint
  class: BackupSaver
  BackupSaver:
    modules:
      - '''model'''
      - '''optim'''
      - '''backup_saver'''
      - '''best_saver'''
      - '''history'''
      - '''lr_scheduler'''
      - '''early_stopping'''
    dirname: '''checkpoint/VOC2007/fasterrcnn_mobilenetv3/'''
    save_interval: 1
    n_saved: 1

engine:
  module: flame.core.engine.torchvision_engine
  class: Trainer
  Trainer:
    dataset: config['data']['train']
    device: '''cuda'''
    max_epochs: 10000

extralibs:
  torch: torch
  iaa: imgaug.augmenters