data:
  test:
    module: torch.utils.data
    class: DataLoader
    DataLoader:
      dataset:
        module: flame.core.data.doc_detection_dataset
        class: DocDetectionDataset
        DocDetectionDataset:
          dirname: '''dataset/VEHICLE_REGISTRATION/DKX_BACK_TYPE_1/test'''
          classes:
            DKX_BACK_TYPE_1: 1
          image_size: (800, 800)
          image_patterns: ['''*.jpg''', '''*.png''', '''*.jpeg''', '''*.JPG''', '''*.PNG''', '''*.JPEG''']
          label_patterns: ['''*.json''']
      batch_size: 2
      shuffle: False
      collate_fn: 'lambda batch:tuple(zip(*batch))'

model:
  module: flame.core.model.maskrcnn
  class: MaskrcnnResnet50FPN
  MaskrcnnResnet50FPN:
    num_classes: 2
    pretrained: False
    pretrained_backbone: False

metrics:
  module: flame.handlers.metrics.metrics
  class: Metrics
  Metrics:
    metrics:
      mAP:
        module: flame.handlers.metrics.mAP
        class: mAP
        mAP:
          num_classes: 2
          iou_threshold: 0.8
          box_format: '''corners'''
          output_transform: 'lambda x: (x[0], x[1])'
    attach_to:
      engine: '''test'''

screenlogger:
  module: flame.handlers.screenlogger
  class: ScreenLogger
  ScreenLogger:
    eval_names:
      - '''test'''

checkpoint_loader:
  module: flame.handlers.checkpoint
  class: CheckpointLoader
  CheckpointLoader:
    checkpoint_path: '''checkpoint/VEHICLE_REGISTRATION/maskrcnn_resnet50fpn/2106281424/best_model_4_mAP=1.0000.pt'''
    mode: '''test'''

predictor:
  module: flame.handlers.predictor
  class: RegionPredictor
  RegionPredictor:
    evaluator_name: '''engine'''
    output_dir: '''checkpoint/VEHICLE_REGISTRATION/maskrcnn_resnet50fpn/2106281424/best_model_4_mAP=1.0000/test'''
    output_img_ext: '''.jpg'''
    output_mask_ext: '''.png'''
    classes:
      DKX_BACK_TYPE_1: [[0, 255, 0], 1]
    image_size: (800, 800)
    thresh_score: 0.8
    thresh_iou_nms: 0.4
    use_pad_to_square: True
    ratio_color_mask_on_image: 0.3
    output_transform: 'lambda x: (x[0], x[-1])'

engine:
  module: flame.core.engine.engine
  class: Evaluator
  Evaluator:
    dataset: config['data']['test']
    device: '''cuda'''

extralibs:
  torch: torch
