data:
  test:
    module: torch.utils.data
    class: DataLoader
    DataLoader:
      dataset:
        module: flame.core.data.labelme_dataset
        class: LabelmeDataset
        LabelmeDataset:
          dirnames:
            - "'dataset/eKYCs/train'"
            - "'dataset/eKYCs/test'"
            - "'dataset/eKYCs/valid'"
          classes:
            BLX: 1
            BLX_BACK: 1
            BLX_OLD: 1
            BLX_BACK_OLD: 1
            CMND: 1
            CMND_BACK: 1
            CCCD: 1
            CCCD_BACK: 1
            CMCC: 1
            CCCD_front_chip: 1
            CCCD_back_chip: 1
            CMQD_A: 1
            CMQD_A_BACK: 1
            CMQD_B: 1
            CMQD_B_BACK: 1
            CMQD_C: 1
            CMQD_C_BACK: 1
            CMQD_D: 1
            CMQD_D_BACK: 1
            CMQD_B_VT: 1
            CMQD_B_VT_BACK: 1
            PASSPORT: 1
            PASSPORT_OTHER: 1
          image_size: (800, 800)
      batch_size: 4
      shuffle: False
      num_workers: 12
      pin_memory: True
      drop_last: False
      collate_fn: "lambda batch:tuple(zip(*batch))"

model:
  module: flame.core.modelmodels.based_maskrcnn_resnet50_fpn
  class: MaskrcnnResnet50FPN
  MaskrcnnResnet50FPN:
    num_classes: 2
    # Box parameters
    box_score_thresh: 0.5
    box_nms_thresh: 0.2

metrics:
  module: flame.handlers.metric_evaluator
  class: Metrics
  Metrics:
    metrics:
      coco_eval:
        module: flame.core.metric.COCO_eval
        class: COCOEvaluator
        COCOEvaluator:
          image_size: (800, 800)
          detection_path: "'checkpoint/eKYC/maskrcnn_resnet50_fpn/2207201241/eEKYC_det_val.json'"
          ground_truth_path: "'checkpoint/eKYC/maskrcnn_resnet50_fpn/2207201241/eEKYC_gt_val.json'"
          classes:
            CARD: 1
          output_transform: "lambda x: (x[0], x[1], x[2])"
    attach_to:
      engine: "'test'"

logger:
  module: flame.handlers.logger
  class: Logger
  Logger:
    logdir: "'checkpoint/eKYC/maskrcnn_resnet50_fpn/2207201241/'"
    logname: "'eKYC'"
    run_mode: "'testing'"

screenlogger:
  module: flame.handlers.screenlogger
  class: ScreenLogger
  ScreenLogger:
    eval_names:
      - "'test'"

checkpoint_loader:
  module: flame.handlers.checkpoint
  class: CheckpointLoader
  CheckpointLoader:
    checkpoint_path: "'checkpoint/eKYC/maskrcnn_resnet50_fpn/2207201241/best_model_7_mAP=0.9932.pt'"
    mode: "'test'"

predictor:
  module: flame.handlers.predictor
  class: Predictor
  Predictor:
    evaluator_name: "'engine'"
    output_dir: "'checkpoint/eKYC/maskrcnn_resnet50_fpn/2207201241/best_model_7_mAP=0.9932/'"
    classes:
      CARD: [[0, 255, 0], 1]
    alpha: 0.3
    draw_class: False
    draw_box: True
    image_size: (800, 800)
    use_pad_to_square: True
    output_transform: "lambda x: (x[0], x[-1])"

engine:
  module: flame.core.engine.engine
  class: Evaluator
  Evaluator:
    dataset: config['data']['test']
    device: "'cuda'"

extralibs:
  torch: torch
