data:
  train:
    module: torch.utils.data
    class: DataLoader
    DataLoader:
      dataset:
        module: flame.core.data.maskrcnn_ekycs_dataset
        class: EkycsDataset
        EkycsDataset:
          dirname: '''dataset/EKYCs/train'''
          classes:
            BLX: 1
            BLX_BACK: 1
            BLX_OLD: 1
            BLX_BACK_OLD: 1
            CMND: 1
            CMND_BACK: 1
            CCCD: 1
            CCCD_BACK: 1
            CMCC: 1
            CCCD_front_chip: 1
            CCCD_back_chip: 1
            CMQD_A: 1
            CMQD_A_BACK: 1
            CMQD_B: 1
            CMQD_B_BACK: 1
            CMQD_C: 1
            CMQD_C_BACK: 1
            CMQD_D: 1
            CMQD_D_BACK: 1
            CMQD_B_VT: 1
            CMQD_B_VT_BACK: 1
            PASSPORT: 1
            PASSPORT_OTHER: 1
          image_size: (800, 800)
          image_patterns: ['''*.jpg''', '''*.png''', '''*.jpeg''', '''*.JPG''', '''*.PNG''', '''*.JPEG''']
          label_patterns: ['''*.xml''']
          transforms:
            - iaa.MotionBlur()
            - iaa.ChangeColorTemperature()
            - iaa.GaussianBlur(sigma=(0, 1))
            - iaa.Grayscale(alpha=(0.0, 1.0))
            - iaa.Add(value=(-50, 50), per_channel=True)
            - iaa.Fliplr(p=0.5)
            - iaa.Flipud(p=0.5)
            - iaa.Crop(percent=(0, 0.1))
            - iaa.Pad(percent=(0, 0.1), keep_size=False)
            - iaa.Rot90(k=[0, 1, 2, 3], keep_size=False)
            - iaa.Affine(rotate=(0, 360), shear=(-2, 2), fit_output=True)
      batch_size: 64
      shuffle: True
      collate_fn: 'lambda batch:tuple(zip(*batch))'
  
  train_eval:
    module: torch.utils.data
    class: DataLoader
    DataLoader:
      dataset:
        module: flame.core.data.maskrcnn_ekycs_dataset
        class: EkycsDataset
        EkycsDataset:
          dirname: '''dataset/EKYCs/train'''
          classes:
            BLX: 1
            BLX_BACK: 1
            BLX_OLD: 1
            BLX_BACK_OLD: 1
            CMND: 1
            CMND_BACK: 1
            CCCD: 1
            CCCD_BACK: 1
            CMCC: 1
            CCCD_front_chip: 1
            CCCD_back_chip: 1
            CMQD_A: 1
            CMQD_A_BACK: 1
            CMQD_B: 1
            CMQD_B_BACK: 1
            CMQD_C: 1
            CMQD_C_BACK: 1
            CMQD_D: 1
            CMQD_D_BACK: 1
            CMQD_B_VT: 1
            CMQD_B_VT_BACK: 1
            PASSPORT: 1
            PASSPORT_OTHER: 1
          image_size: (800, 800)
          image_patterns: ['''*.jpg''', '''*.png''', '''*.jpeg''', '''*.JPG''', '''*.PNG''', '''*.JPEG''']
          label_patterns: ['''*.xml''']
      batch_size: 64
      shuffle: False
      collate_fn: 'lambda batch:tuple(zip(*batch))'
  
  valid:
    module: torch.utils.data
    class: DataLoader
    DataLoader:
      dataset:
        module: flame.core.data.maskrcnn_ekycs_dataset
        class: EkycsDataset
        EkycsDataset:
          dirname: '''dataset/EKYCs/valid'''
          classes:
            BLX: 1
            BLX_BACK: 1
            BLX_OLD: 1
            BLX_BACK_OLD: 1
            CMND: 1
            CMND_BACK: 1
            CCCD: 1
            CCCD_BACK: 1
            CMCC: 1
            CCCD_front_chip: 1
            CCCD_back_chip: 1
            CMQD_A: 1
            CMQD_A_BACK: 1
            CMQD_B: 1
            CMQD_B_BACK: 1
            CMQD_C: 1
            CMQD_C_BACK: 1
            CMQD_D: 1
            CMQD_D_BACK: 1
            CMQD_B_VT: 1
            CMQD_B_VT_BACK: 1
            PASSPORT: 1
            PASSPORT_OTHER: 1
          image_size: (800, 800)
          image_patterns: ['''*.jpg''', '''*.png''', '''*.jpeg''', '''*.JPG''', '''*.PNG''', '''*.JPEG''']
          label_patterns: ['''*.xml''']
      batch_size: 64
      shuffle: False
      collate_fn: 'lambda batch:tuple(zip(*batch))'

model:
  module: flame.core.model.maskrcnn_torchvision
  class: MaskrcnnMobileNetV3
  MaskrcnnMobileNetV3:
    num_classes: 2
    pretrained: True
    pretrained_backbone: True

optim:
  module: torch.optim
  class: SGD
  SGD:
    params: config['model'].parameters()
    lr: 0.005
    momentum: 0.95
    weight_decay: 0.0005

train_evaluator:
  module: flame.handlers.metric_evaluator
  class: MetricEvaluator
  MetricEvaluator:
    dataset: config['data']['train_eval']
    device: '''cuda'''

valid_evaluator:
  module: flame.handlers.metric_evaluator
  class: MetricEvaluator
  MetricEvaluator:
    dataset: config['data']['valid']
    device: '''cuda'''

metrics:
  module: flame.handlers.metrics.metrics
  class: Metrics
  Metrics:
    metrics:
      mAP:
        module: flame.handlers.metrics.mAP
        class: mAP
        mAP:
          num_classes: 2
          iou_threshold: 0.5
          box_format: '''corners'''
          output_transform: 'lambda x: (x[0], x[1])'
    attach_to:
      train_evaluator: '''train'''
      valid_evaluator: '''valid'''

screenlogger:
  module: flame.handlers.screenlogger
  class: ScreenLogger
  ScreenLogger:
    eval_names:
      - '''train''' 
      - '''valid'''

history:
  module: flame.handlers.checkpoint
  class: History

checkpoint_loader:
  module: flame.handlers.checkpoint
  class: CheckpointLoader
  CheckpointLoader:
    checkpoint_path: ''''''
    mode: '''train'''

terminate_on_nan:
  module: flame.handlers.terminate_on_nan
  class: TerminateOnNan

lr_scheduler:
  module: flame.handlers.lr_scheduler
  class: ReduceLROnPlateau
  ReduceLROnPlateau:
    score_name: '''mAP'''
    evaluator_name: '''valid_evaluator'''
    mode: '''max'''
    patience: 5
    verbose: True

# lr_scheduler:
#   module: flame.handlers.lr_scheduler
#   class: StepLR
#   StepLR:
#     score_name: '''mAP'''
#     evaluator_name: '''valid_evaluator'''
#     step_size: 3
#     gamma: 0.1
#     verbose: True

early_stopping:
  module: flame.handlers.early_stopping
  class: EarlyStopping
  EarlyStopping:
    score_name: '''mAP'''
    evaluator_name: '''valid_evaluator'''
    mode: '''max'''
    patience: 5

best_saver:
  module: flame.handlers.checkpoint
  class: BestSaver
  BestSaver:
    dirname: '''checkpoint/EKYCs/maskrcnn_mobilenetv3/'''
    score_name: '''mAP'''
    evaluator_name: '''valid_evaluator'''
    n_saved: 1

backup_saver:
  module: flame.handlers.checkpoint
  class: BackupSaver
  BackupSaver:
    modules:
      - '''model'''
      - '''optim'''
      - '''backup_saver'''
      - '''best_saver'''
      - '''history'''
      - '''lr_scheduler'''
      - '''early_stopping'''
    dirname: '''checkpoint/EKYCs/maskrcnn_mobilenetv3/'''
    save_interval: 1
    n_saved: 1

engine:
  module: flame.core.engine.engine
  class: Trainer
  Trainer:
    dataset: config['data']['train']
    device: '''cuda'''
    max_epochs: 10000

extralibs:
  torch: torch
  iaa: imgaug.augmenters