data:
  test:
    module: torch.utils.data
    class: DataLoader
    DataLoader:
      dataset:
        module: flame.core.data.labelme_dataset
        class: LabelmeDataset
        LabelmeDataset:
          dirnames:
            # - '''dataset/SCENE_TEXT/focused_scene_text_2013/test'''
            # - '''dataset/SCENE_TEXT/incidental_scene_text_2015/test'''
            - '''dataset/SCENE_TEXT/totaltext/valid'''
          classes:
            word: 1
          image_size: None
          mean: [0., 0., 0.]
          std: [1., 1., 1.]
          image_patterns: ['''*.jpg''', '''*.png''', '''*.jpeg''', '''*.JPG''', '''*.PNG''', '''*.JPEG''']
          label_patterns: ['''*.json''']
      batch_size: 1
      shuffle: False
      num_workers: 12
      pin_memory: True
      drop_last: False
      collate_fn: 'lambda batch:tuple(zip(*batch))'

model:
  module: flame.core.model.maskrcnn
  class: MaskrcnnResnet50FPN
  MaskrcnnResnet50FPN:
    num_classes: 2
    pretrained: False
    pretrained_backbone: False
    score_threshold: 0.5
    nms_threshold: 0.2

metrics:
  module: flame.handlers.metrics.metrics
  class: Metrics
  Metrics:
    metrics:
      mAP:
        module: flame.handlers.metrics.mean_average_precision.evaluator
        class: Evaluator
        Evaluator:
          eval_fn:
            module: flame.handlers.metrics.mean_average_precision.mAP
            class: MeanAveragePrecision
            MeanAveragePrecision:
              classes:
                word: 1
              iou_threshold: 0.5
              verbose: True
              method: '''every_point_interpolation'''
          output_transform: 'lambda x: (x[0], x[1])'
    attach_to:
      engine: '''test'''

screenlogger:
  module: flame.handlers.screenlogger
  class: ScreenLogger
  ScreenLogger:
    eval_names:
      - '''test'''

checkpoint_loader:
  module: flame.handlers.checkpoint
  class: CheckpointLoader
  CheckpointLoader:
    checkpoint_path: '''checkpoint/SCENE_TEXT/maskrcnn_resnet50fpn/totaltext/2110300810/best_model_18_mAP=0.8159.pt'''
    mode: '''test'''

predictor:
  module: flame.handlers.mask_predictor
  class: MaskPredictor
  MaskPredictor:
    evaluator_name: '''engine'''
    output_dir: '''checkpoint/SCENE_TEXT/maskrcnn_resnet50fpn/totaltext/2110300810/best_model_18_mAP=0.8159/valid'''
    classes:
      word: [[0, 255, 0], 1]
    alpha: 0.3
    draw_box: False
    image_size: None
    # score_threshold: 0.4
    # iou_threshold: 0.5
    use_pad_to_square: False
    output_transform: 'lambda x: (x[0], x[-1])'

engine:
  module: flame.core.engine.engine
  class: Evaluator
  Evaluator:
    dataset: config['data']['test']
    device: '''cuda'''

extralibs:
  torch: torch
